#!/usr/bin/env bash
#Creates a for loop with a different message at imdex 4, 9 nd 17

x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
		4)
			echo "bad luck from China" ;;
		9)
			echo "bad luck from Japan" ;;
		17)
			echo "bad luck from Italy" ;;
	esac
	((x++))
done
