#!/usr/bin/env bash
#A script that gives indormation aboutb file

file="./school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is nor empty"
	else
		echo "school file does not exist"
	fi

	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
